# Generated by Django 4.1.5 on 2023-01-16 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursoName', models.CharField(max_length=200)),
                ('cursoDescription', models.CharField(blank=True, max_length=200)),
                ('nrc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fotoprofesor', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='TomaRamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alumno', verbose_name='Alumno ok')),
            ],
        ),
        migrations.CreateModel(
            name='AsignarCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrc', models.FloatField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.curso', verbose_name='Curso')),
                ('tomaRamos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tomaramos', verbose_name='Cupos utilizado')),
            ],
        ),
        migrations.AddIndex(
            model_name='asignarcurso',
            index=models.Index(fields=['tomaRamos', 'curso'], name='api_asignar_tomaRam_48c272_idx'),
        ),
    ]
